import {icon,mountPhotoPicker} from './salon-ui.js?v=C26';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const image=v=>typeof v==='string'&&v.startsWith('data:image/')?v:'';
const effects=[['none','原景'],['sakura','櫻花'],['snow','初雪'],['stars','星光']];
export function openProfileScene({person,onSaveName,onSaveProfile,onClose,shop=false}){
 const d=document.createElement('dialog');d.className='profileSceneDialog';d.setAttribute('aria-label',person.name+'的個人頁');let saved={...person},draft={...person},editing=false,saving=false,closed=false;
 d.innerHTML=`<div class="profileScene"><div class="sceneBackdrop"></div><div class="sceneShade"></div><div class="sceneEffects" aria-hidden="true"></div><header class="sceneHeader"><button class="sceneIcon" data-exit aria-label="關閉個人頁">${icon('close')}</button><span data-heading></span>${onSaveProfile?`<button class="sceneEdit" data-edit>${icon('edit')}<span>編輯</span></button>`:'<span></span>'}</header><section class="sceneIdentity"><button class="sceneAvatar" aria-label="放大大頭貼"></button><div class="sceneName"><h1></h1>${onSaveName?`<button class="sceneIcon" data-alias aria-label="修改店家私人稱呼">${icon('edit')}</button>`:''}</div><p class="sceneStatus"></p><p class="sceneBirthday"></p></section><div class="sceneEditBar" hidden><button data-photos>${icon('image')}<span>封面與頭像</span></button><button data-words>${icon('edit')}<span>名字與近況</span></button><button data-effects>${icon('sparkle')}<span>氣氛特效</span></button></div><section class="sceneSheet" hidden></section><p class="sceneFeedback" role="status"></p></div>`;
 document.body.append(d);const q=s=>d.querySelector(s),scene=q('.profileScene'),sheet=q('.sceneSheet');
 function feedback(text){q('.sceneFeedback').textContent=text;}
 function render(){const cover=image(draft.profileCover),photo=image(draft.avatar);q('.sceneBackdrop').style.backgroundImage=cover?`url("${cover}")`:'';q('.sceneAvatar').innerHTML=photo?`<img src="${esc(photo)}" alt="${esc(draft.name)}的大頭貼">`:`<span>${esc((draft.name||'專').slice(0,1))}</span>`;q('h1').textContent=draft.name||'我的空間';q('.sceneStatus').textContent=draft.statusText|| (editing?'寫下一句最近的心情。':'');q('.sceneStatus').hidden=!draft.statusText&&!editing;const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}).split('-'),birthday=Number(draft.birthMonth)===Number(today[1])&&Number(draft.birthDay)===Number(today[2]);q('.sceneBirthday').textContent=birthday?'今天是你的特別日子 · 生日快樂':'';q('.sceneBirthday').hidden=!birthday;const type=effects.some(([key])=>key===draft.profileEffect)?draft.profileEffect:'none',fx=q('.sceneEffects');if(fx.dataset.effect!==type){fx.dataset.effect=type;fx.innerHTML=type==='none'?'':Array.from({length:14},(_,i)=>`<i style="--n:${i};--x:${(i*37+9)%100}%;--delay:${-(i*1.7)}s;--duration:${10+i%5*2}s"></i>`).join('');}if(birthday&&!q('.sceneBalloons')){const balloons=document.createElement('div');balloons.className='birthdayBalloons sceneBalloons';balloons.setAttribute('aria-hidden','true');balloons.innerHTML=Array.from({length:5},(_,i)=>`<i style="--i:${i+1};--balloon:${['#c9b9dc','#e7c995','#a8d1c3','#eebfc9','#9ebed2'][i]}"></i>`).join('');scene.append(balloons);}}
 function exit(){if(saving||closed)return;if(editing){draft={...saved};setEditing(false);render();feedback('');return;}closed=true;d.classList.add('sceneLeaving');setTimeout(()=>d.close(),260);}
 d.addEventListener('close',()=>{d.remove();onClose?.();},{once:true});d.addEventListener('cancel',e=>{e.preventDefault();if(q('.sceneLightbox')){q('.sceneLightbox').remove();return;}if(!sheet.hidden){hideSheet();return;}exit();});q('[data-exit]').onclick=exit;
 function hideSheet(){sheet.hidden=true;sheet.replaceChildren();scene.classList.remove('hasSheet');}
 function showSheet(title,html){sheet.innerHTML=`<div class="sceneSheetHead"><h2>${esc(title)}</h2><button class="sceneIcon" data-dismiss aria-label="關閉編輯區">${icon('close')}</button></div>${html}`;sheet.hidden=false;scene.classList.add('hasSheet');sheet.querySelector('[data-dismiss]').onclick=hideSheet;}
 function setEditing(value){editing=value;hideSheet();scene.classList.toggle('isEditing',value);q('.sceneEditBar').hidden=!value;q('[data-heading]').textContent=value?'編輯個人頁':'';q('[data-exit]').innerHTML=icon(value?'back':'close');q('[data-exit]').setAttribute('aria-label',value?'取消編輯':'關閉個人頁');if(onSaveProfile)q('[data-edit]').innerHTML=value?'儲存':icon('edit')+'<span>編輯</span>';}
 if(onSaveProfile)q('[data-edit]').onclick=async()=>{if(!editing){setEditing(true);render();return;}if(saving)return; saving=true;q('[data-edit]').disabled=true;feedback('正在儲存…');try{await onSaveProfile({...draft});saved={...draft};setEditing(false);render();feedback('已儲存');}catch(e){feedback(e.message||'未儲存，請再試一次');}finally{saving=false;q('[data-edit]').disabled=false;}};
 q('[data-photos]').onclick=()=>{showSheet('封面與大頭貼',`<div class="scenePhotoChoices"><section><h3>全幅封面</h3><label><input type="file" accept="image/*" data-cover></label></section><section><h3>圓形大頭貼</h3><label><input type="file" accept="image/*" data-avatar></label></section></div><p class="sceneNote">封面鋪滿整頁；頭像保留方形照片，可點開放大。</p>`);mountPhotoPicker(sheet.querySelector('[data-cover]'),{initial:draft.profileCover||'',max:1600,budget:360000,cover:true,onChange:value=>{draft.profileCover=value;render();}});mountPhotoPicker(sheet.querySelector('[data-avatar]'),{initial:draft.avatar||'',max:1000,budget:200000,round:true,onChange:value=>{draft.avatar=value;render();}});};
 q('[data-words]').onclick=()=>{showSheet('名字與近況',`<label>${shop?'店名':'你的名字'}<input data-name maxlength="60" value="${esc(draft.name)}"></label><label>最近的心情<textarea data-status maxlength="120" rows="2" placeholder="用一句話，記錄現在的自己">${esc(draft.statusText)}</textarea></label><small class="sceneNote">近況會顯示在個人頁與店家的顧客列表。</small>${shop?'':`<details><summary>電話與生日資料</summary><label>電話<input type="tel" data-phone value="${esc(draft.phone)}"></label><div class="sceneDates"><label>生日月份<input type="number" min="1" max="12" data-month value="${esc(draft.birthMonth)}"></label><label>日期<input type="number" min="1" max="31" data-day value="${esc(draft.birthDay)}"></label></div><label>性別<select data-gender><option value="">不透露</option><option>女性</option><option>男性</option><option>其他</option></select></label></details>`}`);sheet.querySelector('[data-name]').oninput=e=>{draft.name=e.target.value;render();};sheet.querySelector('[data-status]').oninput=e=>{draft.statusText=e.target.value;render();};if(!shop){for(const [key,prop]of [['phone','phone'],['month','birthMonth'],['day','birthDay'],['gender','gender']]){const el=sheet.querySelector('[data-'+key+']');if(key==='gender')el.value=draft.gender||'';el.oninput=()=>{draft[prop]=key==='month'||key==='day'?(el.value?Number(el.value):null):el.value;render();};}}};
 q('[data-effects]').onclick=()=>{showSheet('為今天加一點氣氛',`<div class="sceneEffectChoices">${effects.map(([key,label])=>`<button data-effect="${key}" aria-pressed="${(draft.profileEffect||'none')===key}"><span class="effectSample effect-${key}"></span>${label}</button>`).join('')}</div><p class="sceneNote">效果只呈現在個人頁。已開啟減少動態時，會使用靜態畫面。</p>`);sheet.querySelectorAll('[data-effect]').forEach(b=>b.onclick=()=>{draft.profileEffect=b.dataset.effect;sheet.querySelectorAll('[data-effect]').forEach(x=>x.setAttribute('aria-pressed',x===b));render();});};
 q('.sceneAvatar').onclick=()=>{if(editing){q('[data-photos]').click();return;}const photo=image(draft.avatar);if(!photo)return;const light=document.createElement('div');light.className='sceneLightbox';light.innerHTML=`<button class="sceneIcon" aria-label="返回個人頁">${icon('back')}</button><img src="${esc(photo)}" alt="完整大頭貼">`;scene.append(light);light.querySelector('button').onclick=()=>light.remove();light.querySelector('button').focus();};
 if(onSaveName)q('[data-alias]').onclick=()=>{showSheet('店家私人稱呼',`<form><label>方便你辨識的稱呼<input maxlength="60" required value="${esc(saved.name)}"></label><p class="sceneNote">只改店家端顯示，客人自己的名字不會改變。</p><button type="submit">儲存稱呼</button><p role="status"></p></form>`);const form=sheet.querySelector('form');form.onsubmit=async e=>{e.preventDefault();const name=form.querySelector('input').value.trim();if(!name)return;const b=form.querySelector('button');b.disabled=true;try{await onSaveName(name);saved.name=draft.name=name;render();hideSheet();feedback('私人稱呼已儲存');}catch(e){form.querySelector('[role=status]').textContent=e.message||'儲存失敗';}finally{b.disabled=false;}};};
 render();d.showModal();return d;
}
