const paths={
 settings:'<path d="m9 3-.6 2.2-2 .9-2-.6-2 3.4 1.6 1.6v2.3L2.4 14l2 3.4 2-.6 2 .9L9 20h4l.6-2.3 2-.9 2 .6 2-3.4-1.6-1.2v-2.3l1.6-1.6-2-3.4-2 .6-2-.9L13 3Z"/><circle cx="11" cy="11.5" r="3"/>',
 home:'<path d="m3 10 9-7 9 7M5 9v11h14V9M9 20v-7h6v7"/>',
 chat:'<path d="M20 11a8 8 0 0 1-8 8H5l-3 3v-11a9 9 0 0 1 18 0Z"/><path d="M7 10h8M7 14h5"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="4"/><path d="M7 3v4M17 3v4M3 11h18M8 15h.01M12 15h.01M16 15h.01"/>',
 person:'<circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
 people:'<circle cx="9" cy="7" r="3"/><path d="M3 20v-3a6 6 0 0 1 12 0v3M16 4a3 3 0 0 1 0 6M18 13a5 5 0 0 1 3 5v2"/>',
 image:'<rect x="3" y="3" width="18" height="18" rx="4"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 4-7 5 8"/>',
 board:'<rect x="3" y="4" width="18" height="16" rx="4"/><path d="M7 8h10M7 12h4M7 16h7"/>',
 send:'<path d="m3 4 18 8-18 8 3-8-3-8ZM6 12h15"/>',
 heart:'<path d="M12 20S3 15 3 8a5 5 0 0 1 9-3 5 5 0 0 1 9 3c0 7-9 12-9 12Z"/>',
 reply:'<path d="m9 5-6 6 6 6M3 11h10a7 7 0 0 1 7 7"/>',
 tag:'<path d="M3 4h8l10 10-7 7L3 10V4Z"/><circle cx="7" cy="8" r="1"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',
 chart:'<path d="M4 3v17h17M8 16v-5M13 16V7M18 16V4"/>',
 phone:'<path d="m5 3 4 1 1 5-3 2a14 14 0 0 0 6 6l2-3 5 1 1 4c-1 3-5 3-9 1A22 22 0 0 1 4 12C2 8 2 4 5 3Z"/>',
 pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',
 more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
 check:'<path d="m4 12 5 5L20 6"/>',archive:'<rect x="3" y="4" width="18" height="4" rx="1"/><path d="M5 8v12h14V8M9 12h6"/>',
 block:'<circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/>',camera:'<path d="M4 7h4l2-3h4l2 3h4v14H4Z"/><circle cx="12" cy="13" r="4"/>',plus:'<path d="M12 4v16M4 12h16"/>',back:'<path d="m15 4-8 8 8 8"/>'};
export const icon=(name)=>`<svg class="salonIcon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.more}</svg>`;
export async function compressCanvas(source,max=1000,budget=180000){const canvas=document.createElement('canvas');let edge=Math.min(max,Math.max(source.width||source.naturalWidth,source.height||source.naturalHeight));const sw=source.naturalWidth||source.width,sh=source.naturalHeight||source.height;for(let pass=0;pass<12;pass++){const scale=Math.min(1,edge/Math.max(sw,sh));canvas.width=Math.max(1,Math.round(sw*scale));canvas.height=Math.max(1,Math.round(sh*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(source,0,0,canvas.width,canvas.height);for(const quality of [.85,.72,.58,.44]){const data=canvas.toDataURL('image/jpeg',quality);if(data.length<=budget)return data;}edge=Math.floor(edge*.77);}throw Error('照片無法壓縮，請改選另一張');}
export async function loadPhoto(file){if(!file.type.startsWith('image/')&&!/\.(heic|heif|jpe?g|png|webp)$/i.test(file.name||''))throw Error('請選擇照片');if(file.size>50*1024*1024)throw Error('照片請小於 50 MB');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();return img;}catch(e){throw Error('此照片格式目前無法開啟，請從相簿選取 JPEG／PNG 照片');}finally{URL.revokeObjectURL(url);}}
export function mountPhotoPicker(input,{initial='',max=1000,budget=180000,round=false}={}){
 let current=initial,working=false;
 const box=document.createElement('div');box.className='photoPicker'+(round?' roundPhoto':'');const label=input.closest('label');(label||input).before(box);input.hidden=true;box.append(input);if(label)label.remove();
 const preview=document.createElement('button');preview.type='button';preview.className='photoPreview';preview.setAttribute('aria-label','編輯照片');const actions=document.createElement('div');actions.className='photoActions';actions.innerHTML='<button type="button" data-choose>選擇照片</button><button type="button" data-edit>裁切・旋轉</button><button type="button" data-remove>移除</button>';const status=document.createElement('p');status.className='small';status.setAttribute('role','status');box.append(preview,actions,status);
 const draw=()=>{preview.replaceChildren();if(current){const im=document.createElement('img');im.src=current;im.alt='照片預覽';preview.append(im);}else preview.innerHTML=icon('camera')+'<span>加入照片</span>';actions.querySelector('[data-edit]').textContent=round?'調整位置':'裁切・旋轉';actions.querySelector('[data-edit]').disabled=!current;actions.querySelector('[data-remove]').hidden=!current;};
 const editor=img=>new Promise(resolve=>{const source=document.createElement('canvas'),ratio=Math.min(1,2048/Math.max(img.naturalWidth,img.naturalHeight));source.width=Math.round(img.naturalWidth*ratio);source.height=Math.round(img.naturalHeight*ratio);source.getContext('2d').drawImage(img,0,0,source.width,source.height);const d=document.createElement('dialog');d.className='photoEditor';d.innerHTML='<div class="dialogHead"><button type="button" data-cancel>取消</button><b>調整照片</b><button type="button" data-done>完成</button></div><canvas aria-label="照片裁切預覽"></canvas><div class="cropTools"><label>比例<select data-ratio><option value="0">原比例</option><option value="1">正方形</option><option value="0.75">直式 3:4</option><option value="1.333333">橫式 4:3</option></select></label><button type="button" data-rotate>旋轉 90°</button></div><label>放大<input data-zoom type="range" min="1" max="3" value="1" step="0.01"></label><label>左右位置<input data-x type="range" min="-1" max="1" value="0" step="0.01"></label><label>上下位置<input data-y type="range" min="-1" max="1" value="0" step="0.01"></label><p class="small">調整後按完成，回到卡片預覽；按儲存才會上傳。</p>';document.body.append(d);let rotation=0;const output=d.querySelector('canvas'),rotated=document.createElement('canvas');let cachedRotation=-1;const render=()=>{const swap=rotation%180!==0;if(cachedRotation!==rotation){cachedRotation=rotation;rotated.width=swap?source.height:source.width;rotated.height=swap?source.width:source.height;const rctx=rotated.getContext('2d');rctx.translate(rotated.width/2,rotated.height/2);rctx.rotate(rotation*Math.PI/180);rctx.drawImage(source,-source.width/2,-source.height/2);}const ratio=Number(d.querySelector('[data-ratio]').value)||rotated.width/rotated.height;let w=rotated.width,h=w/ratio;if(h>rotated.height){h=rotated.height;w=h*ratio;}const zoom=Number(d.querySelector('[data-zoom]').value);w/=zoom;h/=zoom;const x=(rotated.width-w)*(Number(d.querySelector('[data-x]').value)+1)/2,y=(rotated.height-h)*(Number(d.querySelector('[data-y]').value)+1)/2;const scale=Math.min(1,(round?1024:1400)/Math.max(w,h));output.width=Math.max(1,Math.round(w*scale));output.height=Math.max(1,Math.round(h*scale));const ctx=output.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,output.width,output.height);ctx.drawImage(rotated,x,y,w,h,0,0,output.width,output.height);};
 if(round){d.classList.add('avatarEditor');d.querySelector('[data-ratio]').value='1';d.querySelector('.cropTools').hidden=true;d.querySelector('.dialogHead b').textContent='調整圓形大頭貼';d.querySelector('.small').textContent='拖動照片、雙指縮放。圓圈是頭像顯示範圍，方形照片會保留供放大查看。';const frame=document.createElement('div');frame.className='avatarCropFrame';output.before(frame);frame.append(output);const mask=document.createElement('div');mask.className='avatarCropMask';frame.append(mask);
 ['x','y'].forEach(k=>d.querySelector('[data-'+k+']').closest('label').hidden=true);
 output.style.touchAction='none';output.style.cursor='grab';let drag=null;const pointers=new Map();let distance=0;
 output.addEventListener('pointerdown',e=>{if(e.button>0)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()];distance=Math.hypot(a.x-b.x,a.y-b.y);}drag={id:e.pointerId,x:e.clientX,y:e.clientY};output.setPointerCapture(e.pointerId);output.style.cursor='grabbing';});
 output.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],next=Math.hypot(a.x-b.x,a.y-b.y),z=d.querySelector('[data-zoom]');if(distance>0)z.value=Math.max(1,Math.min(3,Number(z.value)*next/distance));distance=next;render();return;}if(!drag||drag.id!==e.pointerId){drag={id:e.pointerId,x:e.clientX,y:e.clientY};return;}const z=Number(d.querySelector('[data-zoom]').value),w=Math.min(source.width,source.height)/z,r=output.getBoundingClientRect();for(const [k,delta,total,screen] of [['x',e.clientX-drag.x,source.width,r.width],['y',e.clientY-drag.y,source.height,r.height]]){const input=d.querySelector('[data-'+k+']');if(total>w&&screen)input.value=Math.max(-1,Math.min(1,Number(input.value)-2*delta*w/screen/(total-w)));}drag.x=e.clientX;drag.y=e.clientY;render();});
 const stopDrag=e=>{pointers.delete(e.pointerId);distance=0;drag=null;output.style.cursor='grab';};output.addEventListener('pointerup',stopDrag);output.addEventListener('pointercancel',stopDrag);output.addEventListener('lostpointercapture',stopDrag);}d.querySelectorAll('input,select').forEach(e=>e.oninput=render);d.querySelector('[data-rotate]').onclick=()=>{rotation=(rotation+90)%360;render();};let done=false;const finish=result=>{if(done)return;done=true;resolve(result);d.close();d.remove();};d.querySelector('[data-cancel]').onclick=()=>finish(null);d.oncancel=e=>{e.preventDefault();finish(null);};d.querySelector('[data-done]').onclick=async()=>{const b=d.querySelector('[data-done]');b.disabled=true;try{finish(await compressCanvas(output,max,budget));}catch(e){status.textContent=e.message;b.disabled=false;}};render();d.showModal();});
 const editCurrent=async()=>{if(working||!current)return;working=true;try{const img=new Image();img.src=current;await img.decode();const result=await editor(img);if(result)current=result;draw();}catch(e){status.textContent=e.message;}finally{working=false;}};
 preview.onclick=()=>current?editCurrent():input.click();actions.querySelector('[data-choose]').onclick=()=>input.click();actions.querySelector('[data-edit]').onclick=editCurrent;actions.querySelector('[data-remove]').onclick=()=>{current='';input.value='';status.textContent='';draw();};input.onchange=async()=>{const file=input.files[0];if(!file||working)return;working=true;status.textContent='正在準備照片…';try{const img=await loadPhoto(file);const result=await editor(img);if(result)current=result;status.textContent=result?'照片已準備好，儲存後顯示。':'';draw();}catch(e){status.textContent=e.message;}finally{working=false;input.value='';}};draw();return{get value(){if(working)throw Error('請先完成照片調整');return current;}};
}
export function bindSwipe(shell){const front=shell.querySelector('.swipeFront');let x=0,y=0,base=0,horizontal=false,moved=false;front.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;x=e.clientX;y=e.clientY;base=shell.classList.contains('revealed')?-144:0;horizontal=false;moved=false;});front.addEventListener('pointermove',e=>{if(!e.buttons&&e.pointerType==='mouse')return;const dx=e.clientX-x,dy=e.clientY-y;if(!horizontal){if(Math.abs(dx)<10||Math.abs(dx)<Math.abs(dy)*1.3)return;horizontal=true;front.setPointerCapture(e.pointerId);shell.classList.add('dragging');}moved=true;front.style.transform=`translateX(${Math.max(-154,Math.min(0,base+dx))}px)`;});const end=e=>{if(!horizontal)return;const opened=base+(e.clientX-x)<-55;document.querySelectorAll('.swipeShell.revealed').forEach(other=>{if(other!==shell)other.classList.remove('revealed')});shell.classList.toggle('revealed',opened);shell.classList.remove('dragging');front.style.transform='';horizontal=false;};front.addEventListener('pointerup',end);front.addEventListener('pointercancel',()=>{shell.classList.remove('dragging');front.style.transform='';horizontal=false;});front.addEventListener('click',e=>{if(moved){e.preventDefault();e.stopImmediatePropagation();moved=false;}},true);}

export function mountAttachmentPicker(input,{photos=true}={}){
 const box=document.createElement('div');box.className='attachmentPicker';input.before(box);input.hidden=true;box.append(input);
 const status=document.createElement('p');status.className='attachmentStatus';status.setAttribute('role','status');status.textContent='尚未加入附件';
 const preview=document.createElement('img');preview.className='attachmentPreview';preview.hidden=true;preview.alt='已選照片預覽';let url='';
 const clear=()=>{if(url)URL.revokeObjectURL(url);url='';preview.removeAttribute('src');preview.hidden=true;};
 const choose=(label,key,accept)=>{const b=document.createElement('button');b.type='button';b.className='attachmentChoice';b.innerHTML=icon(key)+'<span>'+label+'</span>';b.onclick=()=>{input.accept=accept;input.click();};box.append(b);};
 choose(photos?'選擇照片或檔案':'選擇檔案',photos?'image':'board',photos?'image/*,application/pdf,text/plain,.pdf,.txt':'application/pdf,text/plain,.pdf,.txt');box.append(preview,status);
 input.addEventListener('change',()=>{clear();const f=input.files[0];status.textContent=f?f.name+' · '+Math.ceil(f.size/1024)+' KB':'尚未加入附件';if(f?.type.startsWith('image/')){url=URL.createObjectURL(f);preview.src=url;preview.hidden=false;}});
 input.closest('dialog')?.addEventListener('close',clear,{once:true});
}
