export function setupGlassSwitches(header,navigate){
 if(!header)return;
 const groups=[...header.querySelectorAll('.headerSwitch')];
 function place(group,button){if(!button)return;const r=button.getBoundingClientRect(),g=group.getBoundingClientRect();group.style.setProperty('--thumb-x',(r.left-g.left)+'px');group.style.setProperty('--thumb-w',r.width+'px');group.querySelectorAll('button[data-header-page]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}
 const update=page=>{groups.forEach(group=>{const buttons=[...group.querySelectorAll('button[data-header-page]')],button=buttons.find(b=>b.dataset.headerPage===page)||buttons.find(b=>b.getAttribute('aria-pressed')==='true')||buttons[0];place(group,button);});};
 groups.forEach(group=>{let start=null,dragged=false;group.querySelectorAll('button[data-header-page]').forEach(b=>b.onclick=()=>{if(dragged){dragged=false;return;}place(group,b);navigate(b.dataset.headerPage);});group.addEventListener('pointerdown',e=>{if(!e.target.closest('button[data-header-page]'))return;start={x:e.clientX,y:e.clientY};dragged=false;});group.addEventListener('pointermove',e=>{if(!start||Math.abs(e.clientX-start.x)<8||Math.abs(e.clientX-start.x)<Math.abs(e.clientY-start.y))return;const g=group.getBoundingClientRect(),w=parseFloat(group.style.getPropertyValue('--thumb-w'))||44;group.style.setProperty('--thumb-x',Math.max(4,Math.min(g.width-w-4,e.clientX-g.left-w/2))+'px');});group.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)<24||Math.abs(dx)<Math.abs(dy)){update('');return;}dragged=true;const buttons=[...group.querySelectorAll('button[data-header-page]')],b=dx>0?buttons.at(-1):buttons[0];place(group,b);navigate(b.dataset.headerPage);setTimeout(()=>dragged=false,0);});group.addEventListener('pointerleave',()=>{start=null;update('');});group.addEventListener('pointercancel',()=>{start=null;update('');});});
 new ResizeObserver(()=>update('')).observe(header);requestAnimationFrame(()=>update(''));return update;
}
export function resumeNotice(bar,{restart=false}={}){if(!bar||bar.hidden||document.hidden)return;const p=bar.querySelector('p');if(!p)return;const animations=p.getAnimations();animations.forEach(a=>{if(restart){a.cancel();a.play();}else if(a.playState!=='running')a.play();});}
