const presets={
 cream:{label:'奶油晨光',background:'#f5f0e7',accent:'#8c7158',secondary:'#b6c6b1',bubble:'#e7d7c1'},
 rose:{label:'玫瑰奶霜',background:'#faf1ed',accent:'#996875',secondary:'#c5b7d4',bubble:'#efd2d7'},
 rain:{label:'雨日青空',background:'#edf3f3',accent:'#557d87',secondary:'#b8c5de',bubble:'#cce4e5'},
 garden:{label:'開心果花園',background:'#f2f4e9',accent:'#697b50',secondary:'#dfbcaa',bubble:'#dce5c7'},
 lilac:{label:'紫芋糖果',background:'#f4eff8',accent:'#846d9b',secondary:'#aacdc5',bubble:'#e5d9ef'}
};
export const themePresets=presets;
const defaults={...presets.cream,preset:'cream',glass:48,blur:7,radius:26,font:'sans',density:'airy',layout:'grid',motif:'cloud',motion:true,greetingEnabled:true,greeting:'哈囉，今天想怎麼整理頭髮？',duration:4,effect:'none'};
const choice=(x,values,fallback)=>values.includes(x)?x:fallback;
const number=(x,min,max,fallback)=>Number.isFinite(Number(x))?Math.min(max,Math.max(min,Number(x))):fallback;
const color=(x,fallback)=>/^#[\da-f]{6}$/i.test(x||'')?x:fallback;
export function normalizeTheme(raw={}){raw=raw&&typeof raw==='object'?raw:{};const d=defaults;return {effect:choice(raw.effect,['none','rain','petals','snow','sun'],d.effect),preset:choice(raw.preset,Object.keys(presets),'cream'),background:color(raw.background,d.background),accent:color(raw.accent,d.accent),secondary:color(raw.secondary,d.secondary),bubble:color(raw.bubble,d.bubble),glass:number(raw.glass,25,85,d.glass),blur:number(raw.blur,0,16,d.blur),radius:number(raw.radius,12,40,d.radius),duration:number(raw.duration,2,8,d.duration),font:choice(raw.font,['sans','serif','round'],d.font),density:choice(raw.density,['airy','compact'],d.density),layout:choice(raw.layout,['grid','list'],d.layout),motif:choice(raw.motif,['cloud','flower','cat','sun','heart','none'],d.motif),motion:raw.motion!==false,greetingEnabled:raw.greetingEnabled!==false,greeting:String(raw.greeting??d.greeting).slice(0,60)};}
function ink(hex){const rgb=hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>.179?'#292722':'#ffffff';}
export function applyTheme(raw,target=document.documentElement){const t=normalizeTheme(raw);const vars={'bg':t.background,'ink':ink(t.background),'accent':t.accent,'accent-ink':ink(t.accent),'secondary':t.secondary,'bubble':t.bubble,'bubble-ink':ink(t.bubble),'glass':`rgba(255,255,255,${t.glass/100})`,'blur':t.blur+'px','radius':t.radius+'px','space':t.density==='airy'?'18px':'12px','font':t.font==='serif'?'Georgia,"Noto Serif TC","Songti TC",serif':t.font==='round'?'ui-rounded,"Arial Rounded MT Bold",system-ui,sans-serif':'system-ui,-apple-system,"PingFang TC",sans-serif'};for(const[k,v]of Object.entries(vars))target.style.setProperty('--salon-'+k,v);target.dataset.salonMotion=t.motion?'on':'off';target.dataset.salonLayout=t.layout;target.dataset.salonMotif=t.motif;return t;}
const icons={cloud:'☁',flower:'✿',cat:'ฅ',sun:'☀',heart:'♡',none:''};
let greetingTimer=0,lastGreeting=0;
export function showGreeting(raw,{force=false,target=document.body}={}){const t=normalizeTheme(raw);playAtmosphere(t,{force,target});if(!t.greetingEnabled||!t.greeting.trim()||(!force&&Date.now()-lastGreeting<60000))return;lastGreeting=Date.now();clearTimeout(greetingTimer);document.querySelector('.salonGreeting')?.remove();const el=document.createElement('div');el.className='salonGreeting';el.dataset.motif=t.motif;el.setAttribute('role','status');const mark=document.createElement('span');mark.className='greetingMark';mark.textContent=icons[t.motif];const text=document.createElement('span');text.textContent=t.greeting;el.append(mark,text);if(['cloud','sun','flower'].includes(t.motif)){el.classList.add('shapedGreeting');const shape=document.createElementNS('http://www.w3.org/2000/svg','svg');shape.setAttribute('viewBox','0 0 260 150');shape.setAttribute('aria-hidden','true');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',t.motif==='cloud'?'M45 130C0 130 0 65 43 62C40 13 112 0 132 40C170 0 225 35 216 68C267 62 276 130 224 130Z':t.motif==='sun'?'M130 3L149 24L178 13L185 42L216 42L209 71L239 87L216 107L222 134L187 131L171 148L146 133L121 149L101 130L70 141L61 115L28 118L39 87L15 68L48 53L46 25L79 30L100 8L113 29Z':'M130 28C165 -10 207 12 197 47C248 35 270 81 226 100C251 137 200 159 174 132C151 165 105 150 107 129C61 166 25 128 53 100C-2 89 12 42 57 49C47 1 109 -5 130 28Z');shape.append(path);el.prepend(shape);mark.hidden=true;}el.style.setProperty('--greeting-duration',t.duration+'s');if(!t.motion||matchMedia('(prefers-reduced-motion: reduce)').matches)el.classList.add('still');target.append(el);greetingTimer=setTimeout(()=>el.remove(),t.duration*1000);}
export function hideGreeting(){stopAtmosphere();clearTimeout(greetingTimer);document.querySelector('.salonGreeting')?.remove();}
export function mountThemeEditor(body,raw,onSave){let draft=normalizeTheme(raw);body.innerHTML=`<p class="sectionIntro">你的空間，由你配色。先預覽，滿意後再發布到店家與客戶端。</p><div class="themePresets">${Object.entries(presets).map(([id,p])=>`<button type="button" class="themePreset" data-preset="${id}" style="--swatch:${p.bubble};--tone:${p.secondary}"><span></span>${p.label}</button>`).join('')}</div><section class="themePreview" aria-label="主題預覽"><div class="previewTop">專屬空間 <span>✦</span></div><div class="previewContent"><small>讓日常，輕盈一點</small><h3>今天，也好好照顧自己。</h3><div class="previewCards"><div>☀ 預約時光</div><div>✿ 空間消息</div></div><p class="previewOther">你好，想詢問剪髮時間。</p><p class="previewMine">當然可以，慢慢跟我說。</p></div><div class="previewBottom">聊天　 ·　 預約</div></section><div class="themeFields"><label>背景<input type="color" data-theme="background"></label><label>重點色<input type="color" data-theme="accent"></label><label>點綴色<input type="color" data-theme="secondary"></label><label>自己的泡泡<input type="color" data-theme="bubble"></label></div><div class="settingsGroup"><h3>透亮與形狀</h3><label>玻璃白度（低＝較透明）<input type="range" min="25" max="85" data-theme="glass"></label><label>玻璃霧度（低＝較清晰）<input type="range" min="0" max="16" data-theme="blur"></label><label>圓角（低＝圓角方形，高＝膠囊）<input type="range" min="12" max="40" data-theme="radius"></label><label>字體<select data-theme="font"><option value="sans">清楚黑體</option><option value="serif">文青明體</option><option value="round">柔和圓體（依裝置字型）</option></select></label><label>留白<select data-theme="density"><option value="airy">舒適留白</option><option value="compact">俐落緊湊</option></select></label><label>店家功能排列<select data-theme="layout"><option value="grid">雙欄卡片</option><option value="list">單欄卡片</option></select></label></div><div class="settingsGroup"><h3>聊天背景氣氛</h3><label>輕量特效（播放 12 秒後停止）<select data-theme="effect"><option value="none">關閉</option><option value="rain">雨滴</option><option value="petals">櫻花</option><option value="snow">飄雪</option><option value="sun">暖陽</option></select></label><p class="small">只在進入聊天時短暫播放，不連氣象、不取得位置，也不寫入聊天紀錄。</p><h3>進入聊天的小招呼</h3><label><input type="checkbox" data-theme="greetingEnabled"> 顯示招呼</label><label>招呼文字<input maxlength="60" data-theme="greeting"></label><label>小圖案<select data-theme="motif"><option value="cloud">雲朵</option><option value="flower">小花</option><option value="cat">貓咪</option><option value="sun">晴天</option><option value="heart">心情愛心</option><option value="none">簡潔膠囊</option></select></label><label>停留秒數<input type="range" min="2" max="8" data-theme="duration"></label><label><input type="checkbox" data-theme="motion"> 水滴彈性與進出動畫</label><button type="button" class="softBtn" id="themeGreetingTest">播放招呼預覽</button><p class="small">天氣、動物是裝飾圖案，不會取得位置或查詢天氣。快速反覆進出不會一直跳出招呼；尊重手機「減少動態效果」設定。</p></div><div class="toolbar"><button id="themePublish">發布主題</button><button id="themeReset" class="softBtn">還原上次發布</button></div><p id="themeStatus" role="status" class="small">調整預覽不會寫入雲端。</p>`;
 const preview=body.querySelector('.themePreview'),fields=[...body.querySelectorAll('[data-theme]')];const paint=()=>{applyTheme(draft,preview);body.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===draft.preset)));};const fill=()=>{fields.forEach(el=>{if(el.type==='checkbox')el.checked=draft[el.dataset.theme];else el.value=draft[el.dataset.theme];});paint();};fields.forEach(el=>el.oninput=()=>{draft=normalizeTheme({...draft,[el.dataset.theme]:el.type==='checkbox'?el.checked:el.value});paint();body.querySelector('#themeStatus').textContent='預覽中，尚未發布。';});body.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{draft=normalizeTheme({...draft,...presets[b.dataset.preset],preset:b.dataset.preset});fill();});body.querySelector('#themeGreetingTest').onclick=()=>{preview.scrollIntoView({behavior:'smooth',block:'center'});showGreeting(draft,{force:true,target:preview});};body.querySelector('#themeReset').onclick=()=>{draft=normalizeTheme(raw);fill();};body.querySelector('#themePublish').onclick=async e=>{const b=e.currentTarget;b.disabled=true;const saved={...draft};try{await onSave(saved);raw=saved;applyTheme(saved);body.querySelector('#themeStatus').textContent='已發布。客戶端開啟時會同步套用；已開啟的客戶端會收到設定更新。';}catch(err){body.querySelector('#themeStatus').textContent='發布失敗：'+err.message;}finally{b.disabled=false;}};fill();}

let atmosphereTimer,lastAtmosphere=0;
export function stopAtmosphere(){clearTimeout(atmosphereTimer);document.querySelectorAll('.salonAtmosphere').forEach(x=>x.remove());}
export function playAtmosphere(raw,{force=false,target=document.body}={}){const t=normalizeTheme(raw);if(t.effect==='none'||!t.motion||document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches||(!force&&Date.now()-lastAtmosphere<60000))return;lastAtmosphere=Date.now();stopAtmosphere();const layer=document.createElement('div');layer.className='salonAtmosphere '+t.effect;layer.setAttribute('aria-hidden','true');for(let i=0;i<(t.effect==='sun'?1:12);i++){const dot=document.createElement('i');dot.style.setProperty('--x',((i*29+7)%100)+'%');dot.style.setProperty('--delay',-(i%5)+'s');dot.style.setProperty('--drift',(i%2?45:-35)+'px');layer.append(dot);}target.append(layer);atmosphereTimer=setTimeout(stopAtmosphere,12000);}
if(typeof document!=='undefined')document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAtmosphere();});
