import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const src=await readFile(new URL('../salon-theme.js',import.meta.url),'utf8');
const {normalizeTheme,applyTheme}=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));
const t=normalizeTheme({glass:900,blur:-1,radius:0,duration:99,font:'url(unsafe)',background:'red;display:none',greeting:'a'.repeat(100)});
assert.equal(t.glass,85);assert.equal(t.blur,0);assert.equal(t.radius,12);assert.equal(t.duration,8);assert.equal(t.font,'sans');assert.match(t.background,/^#[0-9a-f]{6}$/i);assert.equal(t.greeting.length,60);
assert.deepEqual(normalizeTheme(null),normalizeTheme());
const vars={},target={style:{setProperty:(k,v)=>vars[k]=v},dataset:{}};
applyTheme({bubble:'#000000',accent:'#ffffff',motion:false,layout:'list'},target);
assert.equal(vars['--salon-bubble-ink'],'#ffffff');assert.equal(vars['--salon-accent-ink'],'#292722');assert.equal(target.dataset.salonMotion,'off');assert.equal(target.dataset.salonLayout,'list');
console.log('PASS: untrusted theme values, clamps, null defaults, contrasting text, reduced motion and scoped preview variables.');
